dist:     trusty
sudo:     required
language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

matrix:
    include:
        - os:  linux
          env: COMMIT_BUNDLE=ON

    exclude:
        - os:       osx
          compiler: gcc

install:
    - source install.sh

script:
    - source build.sh

deploy:
    provider:     script
    skip_cleanup: true

    script: source deploy.sh

    on:
        branch:    master
        condition: $COMMIT_BUNDLE == ON

#       tags: true