dist:     trusty
sudo:     required
language: cpp

compiler:
    - gcc
    - clang

install:
    - source install.sh

script:
    - source build.sh

notifications:
    webhooks:
        on_success: always
        urls:
            - http://ioninja.com:5005/travis-ci
